services:
  - type: web
    name: quiz-backend
    rootDir: backend  # Changed from demo-quiz-app/backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /var/data/quiz_system.db
      - key: CORS_ORIGIN
        value: https://YOUR-FRONTEND.onrender.com
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

  - type: static
    name: quiz-frontend
    rootDir: frontend-vite  # Changed from demo-quiz-app/frontend-vite
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://YOUR-BACKEND.onrender.com